### PR TITLE
feat: add authentication to bullboard

### PR DESCRIPTION
**Pull request by Yash-Singh1**

### CODE REVIEW

**Comment by pastelsky** [comment]
Thanks for this ❤️ 
Clearly I've been a little lazy :)

**Review by pastelsky — APPROVED** [review]

**Comment by Yash-Singh1** [comment]
@pastelsky Forgot to mention in PR comment, but I sent you an email with more details regarding this.

--
Thanks,
Yash

**Comment by pastelsky** [comment]
@Yash-Singh1 I can't seem to find any — did a quick search. What was the subject? Also my email should be on my github profile.

**Comment by Yash-Singh1** [comment]
> What was the subject?

"TSDocs Security Vulnerability Disclosure"

> Also my email should be on my github profile.

Yes I checked, I used the same email as your GitHub profile.

**Pull request merged**
